# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "N-V-__8AAFrtpQI1j9eOv7aN3lt3eH1TJfH4npAdRIrg2gGH";
    path = fetchzip {
      url = "https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v3.6.0.tar.gz";
      hash = "sha256-yzGBkrqh+T/5GS66xL5zJstCmvcfG09TfxqA3F8UPJg=";
    };
  }
  {
    name = "N-V-__8AAHipPQF9UuLPiaV1CtJzZIxvTN61tMGdFx8LGjIV";
    path = fetchzip {
      url = "https://github.com/curl/curl/releases/download/curl-8_8_0/curl-8.8.0.tar.gz";
      hash = "sha256-Gqfe8iiC8aCBiuUVO6VYqW5DmqgSv5oS4XvMfQgbwFw=";
    };
  }
  {
    name = "N-V-__8AAJj_QgDBhU17TCtcvdjOZZPDfkvxrEAyZkc14VN8";
    path = fetchzip {
      url = "https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.gz";
      hash = "sha256-acY8yFzIRYbrZ2CGODoxLnZuppsP6KZy19I9Yy77pfc=";
    };
  }
  {
    name = "curl-0.3.1-P4tT4b_JAAC2bpWR1_NjsHTrg_Ufz2mmojU-e-y9k_99";
    path = fetchzip {
      url = "https://github.com/jiacai2050/zig-curl/archive/refs/tags/v0.3.1.tar.gz";
      hash = "sha256-QtjpfskxPuN8rz9QKo7K0kf0rvMPDlxtcOHRy0XP0pI=";
    };
  }
  {
    name = "zigcli-0.3.0-ORC7jBOfAgCIb2bCGaDWiuoJ8oBkoT9-ftj0c2SBrTX0";
    path = fetchzip {
      url = "https://github.com/jiacai2050/zigcli/archive/refs/tags/v0.3.0.zip";
      hash = "sha256-WSushe8yJUtPrOTnUqBLk5ZYGzXjBBSzdjpLVDlHwTs=";
    };
  }
  {
    name = "ziglangSet-0.0.1-VUjv0hoUAgAxi3Zu4l_6QRnST7KqzKJW9n0FV1WKfweT";
    path = fetchzip {
      url = "https://github.com/deckarep/ziglang-set/archive/d63232266deb61c334da8f198e32a3fb51012650.tar.gz";
      hash = "sha256-18eI84psLl3BjdG6mdzGr+EM5nqEez61odyj1pLXpfA=";
    };
  }
]
