#!/bin/sh
echo In 'systemd-ask-password' with args $*
export SYSTEMD_ASK_PASSWORD_CALLED=1
if [[ "${SYSTEMD_ASK_PASSWORD_KEYS}" != "" ]]; then
  for kv in ${SYSTEMD_ASK_PASSWORD_KEYS}; do
    keyctl add user "${kv%:*}" "${kv#*:}" @u
  done
fi
exit 0
